{{/*
Copyright RisingWave Labs.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "risingwave-operator.serviceAccountName" . }}
  labels:
    {{- include "risingwave-operator.labels" . | nindent 4 }}
  {{- $annotations := (include "risingwave-operator.annotations" . ) | trim }}
  annotations:
    {{- if $annotations }}
    {{ nindent 4 $annotations }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
