apiVersion: v1
entries:
  etcd:
  - annotations:
      category: Database
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 3.5.9
    created: "2023-10-17T15:57:20.435650691+01:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: etcd is a distributed key-value store designed to securely store
      data across a cluster. etcd is widely used in production on account of its reliability,
      fault-tolerance and ease of use.
    digest: 528e70c4673eb46daf78d92faf9dbd7a0260dd37cb9694e6404ec7931f86dec3
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/etcd/img/etcd-stack-220x234.png
    keywords:
    - etcd
    - cluster
    - database
    - cache
    - key-value
    maintainers:
    - name: VMware, Inc.
      url: https://github.com/bitnami/charts
    name: etcd
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/etcd
    urls:
    - http://localhost:8080/charts/etcd-9.1.0.tgz
    version: 9.1.0
  minio:
  - annotations:
      category: Infrastructure
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 2023.7.18
    created: "2023-10-17T15:57:20.437707617+01:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: MinIO(R) is an object storage server, compatible with Amazon S3 cloud
      storage service, mainly used for storing unstructured data (such as photos,
      videos, log files, etc.).
    digest: 0b26651afff43034c2daa99c46bcdf2c90d2d1b801117fb1078002d5ee48c3ea
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/minio/img/minio-stack-220x234.png
    keywords:
    - minio
    - storage
    - object-storage
    - s3
    - cluster
    maintainers:
    - name: VMware, Inc.
      url: https://github.com/bitnami/charts
    name: minio
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/minio
    urls:
    - http://localhost:8080/charts/minio-12.6.12.tgz
    version: 12.6.12
  risingwave:
  - apiVersion: v2
    appVersion: v1.2.0
    created: "2023-10-17T15:57:20.433217998+01:00"
    dependencies:
    - name: etcd
      repository: https://charts.bitnami.com/bitnami
      tags:
      - etcd
      version: 9.1.*
    - condition: stateStore.minio.enabled
      name: minio
      repository: https://charts.bitnami.com/bitnami
      tags:
      - minio
      version: 12.6.*
    description: The distributed streaming database SQL stream processing with Postgres-like
      experience.
    digest: c49d3faacee9a42f6fc335924a7a65bd9f89e0ca1a4d08d980054cefba73f520
    home: https://www.risingwave.com
    icon: https://avatars.githubusercontent.com/u/77175557?s=48&v=4
    keywords:
    - risingwave
    - streaming-processing
    - cloud-native
    - real-time
    maintainers:
    - name: RisingWave Labs
      url: https://www.risingwave-labs.com
    name: risingwave
    type: application
    urls:
    - http://localhost:8080/risingwave-0.1.22.tgz
    version: 0.1.22
generated: "2023-10-17T15:57:20.427867377+01:00"
